language: "en"

audio_ref: "data/ref/english/trump.mp3"

# Data filtering parameters
data_config:
  file: "data/text/english.txt"
  min_phonemes: 8
  max_phonemes: 2000

# Voice generating (cloning) parameters
generation_config:
  batch_size: 1
  speed: 1.0
  # num_steps: 1
  # t_shift: 1
  # p_temperature: 1
  # c_temperature: 1